services:
  webapp1:
    build: ../project/
#    ports:
#      - "8081:80"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - redisnet

  webapp2:
    build: ../project/
#    ports:
#      - "8082:80"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - redisnet

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Expose port 8080 for the load balancer
#      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the NGINX configuration file
#      - ../nginx/certs:/etc/nginx/certs:ro
    networks:
      - redisnet

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - redisnet

networks:
  redisnet:
    driver: bridge 
    ipam:
      config:
          - subnet: "172.20.0.0/29"